//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName1 { get; set; }
        public string lastName2 { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int role { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
